Add unit tests for endpoints
NYCUITSC/NYCUTDX-backend pull request #12
Opened 2024-09-10 08:00 UTC by YenPeiChen07

To be updated.

2024-09-17 11:13 UTC, gift-li commented
由於 Action 包含 comment 功能，導致出現 checks 失敗的 warning
已於 dev 分支移除該步驟，可能此 PR 再推送一個 commit 能排除此 warning

2024-09-21 05:25 UTC, gift-li requested changes
- 沒有大問題，local 執行 test 也都正常
---
- 以下兩點再麻煩調整，處理完就能合併
  - 將 test 相關的架構圖、寫測試的方法和指令 (就是 PR 的 comment) 放入 README.md 中
  - 根據 PR check 彈出的建議，需要將 `workflows/unit-test.yml` 的 setup-go@v4 升級為 v5，使其支援 node 20
    - https://github.com/actions/setup-go?tab=readme-ov-file#v5

2024-09-21 05:25 UTC, gift-li commented on .github/workflows/unit-test.yml
> +        uses: actions/setup-go@v4
這邊需要升級成 v5

2024-09-21 08:16 UTC, YenPeiChen07 commented
> * 以下兩點再麻煩調整，處理完就能合併
>   
>   * 將 test 相關的架構圖、寫測試的方法和指令 (就是 PR 的 comment) 放入 README.md 中
>   * 根據 PR check 彈出的建議，需要將 `workflows/unit-test.yml` 的 setup-go@v4 升級為 v5，使其支援 node 20
>     
>     * https://github.com/actions/setup-go?tab=readme-ov-file#v5

已更新版本以及`README.md`。

2024-09-22 05:24 UTC, gift-li approved these changes
lgtm

2024-09-22 05:26 UTC, merged